const strings = {
  ar: {
    nav_features: 'المميزات',
    nav_screens: 'لقطات الشاشة',
    nav_pricing: 'الأسعار',
    nav_download: 'التحميل',
    nav_contact: 'تواصل معنا',
    nav_trial: 'اطلب تجربة مجانية',
    hero_badge: 'نظام متكامل لإدارة أعمالك',
    hero_title: 'من نقطة البيع إلى المحاسبة الكاملة — في منصة واحدة',
    hero_subtitle:
      'ASKERP يجمع البيع، المخزون، المحاسبة، والفواتير الإلكترونية في حل سريع وآمن — سطح مكتب وموبايل — مصمم للتجزئة والجملة والمكتبات في مصر والمنطقة.',
    hero_cta_trial: 'ابدأ نسختك التجريبية',
    hero_cta_whatsapp: 'تواصل عبر واتساب',
    hero_stat_modules: 'وحدة أعمال',
    hero_stat_platforms: 'منصات',
    hero_stat_support: 'دعم مباشر',
    features_title: 'كل ما تحتاجه لإدارة نشاطك',
    features_subtitle: 'من أول عملية بيع حتى التقارير المالية — بدون تعقيد.',
    f_pos_title: 'نقطة بيع احترافية',
    f_pos_desc: 'بيع سريع، باركود، خصومات، شيفتات، دفع نقدي وبطاقة وأقساط.',
    f_inv_title: 'مخزون ومشتريات',
    f_inv_desc: 'أصناف، مستودعات، تحويلات، صلاحية، باركود، ومتابعة حركة المخزون.',
    f_acc_title: 'محاسبة متكاملة',
    f_acc_desc: 'دليل حسابات، قيود، خزائن، إقفال فترات مالية، وتسوية بنكية.',
    f_einv_title: 'فواتير إلكترونية',
    f_einv_desc: 'دعم ZATCA وETA والامتثال الإقليمي مع أرشفة UBL وتتبع الإرسال.',
    f_mob_title: 'تطبيق موبايل',
    f_mob_desc: 'بيع من الهاتف مع مزامنة، باركود، وعمل أوفلاين عند انقطاع الشبكة.',
    f_rep_title: 'تقارير ولوحة تحكم',
    f_rep_desc: 'مؤشرات يومية، تقارير مالية ومخزنية، وتحليلات تنفيذية.',
    f_multi_title: 'فروع وشركات متعددة',
    f_multi_desc: 'إدارة أكثر من فرع أو شركة من نفس النظام بصلاحيات دقيقة.',
    f_hr_title: 'موارد بشرية',
    f_hr_desc: 'حضور وانصراف، إجازات، رواتب، وعمولات المبيعات.',
    f_pay_title: 'بوابات دفع وتكامل',
    f_pay_desc: 'ربط بوابات الدفع، Shopify، وإشعارات Webhook للأنظمة الخارجية.',
    f_sec_title: 'أمان ونسخ احتياطي',
    f_sec_desc: 'تشفير، سجل تدقيق، نسخ محلي وسحابي، وإشعارات Telegram.',
    screens_title: 'شاشات من داخل النظام',
    screens_subtitle: 'واجهة عربية واضحة — سريعة على سطح المكتب والموبايل.',
    screen_dash: 'لوحة التحكم',
    screen_pos: 'نقطة البيع',
    screen_mobile: 'تطبيق الموبايل',
    screen_reports: 'التقارير',
    screen_einv: 'الفواتير الإلكترونية',
    pricing_title: 'ابدأ بتجربة مجانية',
    pricing_subtitle: 'جرّب النظام كاملاً قبل الاشتراك — السعر يُحدد حسب احتياجات نشاطك.',
    pricing_trial_title: 'نسخة تجريبية',
    pricing_trial_price: 'مجاناً',
    pricing_trial_desc: 'وصول كامل للتجربة مع إعداد أولي ودعم فني مباشر.',
    pricing_trial_li1: 'تثبيت وإعداد قاعدة البيانات',
    pricing_trial_li2: 'تدريب سريع على الوحدات الأساسية',
    pricing_trial_li3: 'دعم عبر واتساب أثناء التجربة',
    pricing_trial_cta: 'اطلب تجربتك الآن',
    pricing_full_title: 'الاشتراك الكامل',
    pricing_full_price: 'حسب الاتفاق',
    pricing_full_desc: 'ترخيص مخصص بعد التجربة — باقات تناسب حجم نشاطك.',
    pricing_full_li1: 'سطح مكتب + API موبايل + تطبيق هاتف',
    pricing_full_li2: 'تحديثات وصيانة مستمرة',
    pricing_full_li3: 'تخصيص حسب الفروع والصلاحيات',
    pricing_full_cta: 'استفسر عن السعر',
    download_title: 'كيف تحصل على البرنامج؟',
    download_subtitle:
      'نوصي بالتواصل المباشر — نرسل لك النسخة المناسبة ونساعدك في التثبيت والإعداد خطوة بخطوة.',
    dl_desktop_title: 'سطح المكتب',
    dl_desktop_desc: 'Windows 10/11 مع SQL Server — الحل الرئيسي للمحاسبة والتقارير.',
    dl_desktop_cta: 'اطلب نسخة سطح المكتب',
    dl_mobile_title: 'تطبيق الموبايل',
    dl_mobile_desc: 'Android وiOS — يتصل بسيرفر شركتك للبيع والمزامنة.',
    dl_mobile_cta: 'اطلب تطبيق الموبايل',
    dl_api_title: 'Mobile API',
    dl_api_desc: 'لربط الفروع والأجهزة — يُثبّت على سيرفرك مع مفتاح API آمن.',
    dl_api_cta: 'استفسر عن الإعداد',
    download_note:
      'لماذا التواصل المباشر؟ لأن كل عميل يحتاج إعداداً مختلفاً — قاعدة بيانات، فروع، فوترة إلكترونية — ونضمن لك تشغيلاً سليماً من أول يوم.',
    contact_title: 'تواصل معنا',
    contact_subtitle: 'فريق ASKERP جاهز يرد عليك ويرتّب النسخة التجريبية.',
    contact_whatsapp: 'واتساب',
    contact_email: 'البريد الإلكتروني',
    contact_email_action: 'راسلنا بالبريد',
    page_title: 'ASKERP',
    contact_facebook: 'فيسبوك',
    footer_tagline: 'نظام نقاط بيع وERP متكامل — سطح مكتب وموبايل.',
    footer_rights: '© 2026 ASKERP. جميع الحقوق محفوظة.',
    nav_menu_aria: 'فتح القائمة',
    float_whatsapp_aria: 'تواصل عبر واتساب'
  },
  en: {
    nav_features: 'Features',
    nav_screens: 'Screenshots',
    nav_pricing: 'Pricing',
    nav_download: 'Download',
    nav_contact: 'Contact',
    nav_trial: 'Request free trial',
    hero_badge: 'All-in-one business platform',
    hero_title: 'From POS to full accounting — in one platform',
    hero_subtitle:
      'ASKERP unifies sales, inventory, accounting, and e-invoicing in a fast, secure desktop and mobile solution — built for retail, wholesale, and bookstores across Egypt and the region.',
    hero_cta_trial: 'Start your free trial',
    hero_cta_whatsapp: 'Chat on WhatsApp',
    hero_stat_modules: 'business modules',
    hero_stat_platforms: 'platforms',
    hero_stat_support: 'direct support',
    features_title: 'Everything you need to run your business',
    features_subtitle: 'From the first sale to financial reports — without the complexity.',
    f_pos_title: 'Professional POS',
    f_pos_desc: 'Fast checkout, barcodes, discounts, shifts, cash, card, and installment payments.',
    f_inv_title: 'Inventory & purchases',
    f_inv_desc: 'Items, warehouses, transfers, expiry dates, barcodes, and stock movement tracking.',
    f_acc_title: 'Integrated accounting',
    f_acc_desc: 'Chart of accounts, journals, treasuries, period close, and bank reconciliation.',
    f_einv_title: 'E-invoicing',
    f_einv_desc: 'ZATCA, ETA, and regional compliance with UBL archiving and submission tracking.',
    f_mob_title: 'Mobile app',
    f_mob_desc: 'Sell from your phone with sync, barcode scanning, and offline mode.',
    f_rep_title: 'Reports & dashboard',
    f_rep_desc: 'Daily KPIs, financial and inventory reports, and executive analytics.',
    f_multi_title: 'Multi-branch & multi-company',
    f_multi_desc: 'Manage multiple branches or companies from one system with fine-grained permissions.',
    f_hr_title: 'Human resources',
    f_hr_desc: 'Attendance, leave, payroll, and sales commissions.',
    f_pay_title: 'Payments & integrations',
    f_pay_desc: 'Payment gateways, Shopify, and webhook notifications for external systems.',
    f_sec_title: 'Security & backup',
    f_sec_desc: 'Encryption, audit log, local and cloud backup, and Telegram alerts.',
    screens_title: 'Screens from inside the system',
    screens_subtitle: 'Clear Arabic-first UI — fast on desktop and mobile.',
    screen_dash: 'Dashboard',
    screen_pos: 'Point of sale',
    screen_mobile: 'Mobile app',
    screen_reports: 'Reports',
    screen_einv: 'E-invoicing',
    pricing_title: 'Start with a free trial',
    pricing_subtitle: 'Try the full system before you subscribe — pricing is tailored to your business.',
    pricing_trial_title: 'Trial version',
    pricing_trial_price: 'Free',
    pricing_trial_desc: 'Full trial access with initial setup and direct technical support.',
    pricing_trial_li1: 'Database installation and setup',
    pricing_trial_li2: 'Quick training on core modules',
    pricing_trial_li3: 'WhatsApp support during the trial',
    pricing_trial_cta: 'Request your trial now',
    pricing_full_title: 'Full subscription',
    pricing_full_price: 'On request',
    pricing_full_desc: 'Custom license after trial — plans that fit your business size.',
    pricing_full_li1: 'Desktop + mobile API + phone app',
    pricing_full_li2: 'Ongoing updates and maintenance',
    pricing_full_li3: 'Customization for branches and permissions',
    pricing_full_cta: 'Ask about pricing',
    download_title: 'How do you get the software?',
    download_subtitle:
      'We recommend direct contact — we send the right build and guide you through installation step by step.',
    dl_desktop_title: 'Desktop',
    dl_desktop_desc: 'Windows 10/11 with SQL Server — the main hub for accounting and reports.',
    dl_desktop_cta: 'Request desktop version',
    dl_mobile_title: 'Mobile app',
    dl_mobile_desc: 'Android and iOS — connects to your company server for sales and sync.',
    dl_mobile_cta: 'Request mobile app',
    dl_api_title: 'Mobile API',
    dl_api_desc: 'For branches and devices — installed on your server with a secure API key.',
    dl_api_cta: 'Ask about setup',
    download_note:
      'Why direct contact? Every customer needs different setup — database, branches, e-invoicing — and we make sure you run smoothly from day one.',
    contact_title: 'Contact us',
    contact_subtitle: 'The ASKERP team is ready to reply and arrange your trial.',
    contact_whatsapp: 'WhatsApp',
    contact_email: 'Email',
    contact_email_action: 'Send us an email',
    page_title: 'ASKERP',
    contact_facebook: 'Facebook',
    footer_tagline: 'Integrated POS & ERP — desktop and mobile.',
    footer_rights: '© 2026 ASKERP. All rights reserved.',
    nav_menu_aria: 'Open menu',
    float_whatsapp_aria: 'Chat on WhatsApp'
  }
};
